// let meetColNumbers = document.querySelectorAll('.meet-col')
// console.log(meetColNumbers)
// let numberIs = document.createElement('h1')
// console.log(numberIs.style.textContent = 370)
// numberIs.append(meetColNumbers)